/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BeatIndicator: typeof import('./src/components/BeatIndicator.vue')['default']
    BeatIndicatorInfoDialog: typeof import('./src/components/BeatIndicatorInfoDialog.vue')['default']
    BeatIndicatorItem: typeof import('./src/components/BeatIndicatorItem.vue')['default']
    BeatsIndicator: typeof import('./src/components/BeatsIndicator.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CheckboxControl: typeof import('./src/components/CheckboxControl.vue')['default']
    CheckBoxControl: typeof import('./src/components/CheckBoxControl.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ConfirmOverwriteDialog: typeof import('./src/components/ConfirmOverwriteDialog.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InfoDialog: typeof import('./src/components/InfoDialog.vue')['default']
    InfoModal: typeof import('./src/components/InfoModal.vue')['default']
    InstallPrompt: typeof import('./src/components/InstallPrompt.vue')['default']
    Label: typeof import('./src/components/Label.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MetronomeControls: typeof import('./src/components/MetronomeControls.vue')['default']
    MetronomeGrid: typeof import('./src/components/MetronomeGrid.vue')['default']
    MetronomeSection: typeof import('./src/components/MetronomeSection.vue')['default']
    MetronomeTempos: typeof import('./src/components/MetronomeTempos.vue')['default']
    MyButton: typeof import('./src/components/MyButton.vue')['default']
    PresetsDialog: typeof import('./src/components/PresetsDialog.vue')['default']
    PresetsModal: typeof import('./src/components/PresetsModal.vue')['default']
    SavePresetDialog: typeof import('./src/components/SavePresetDialog.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SelectButtonControl: typeof import('./src/components/SelectButtonControl.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    SliderControl: typeof import('./src/components/SliderControl.vue')['default']
    TempoVariables: typeof import('./src/components/TempoVariables.vue')['default']
    ToggleThemeButton: typeof import('./src/components/ToggleThemeButton.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
